In [4]:
my_list = [1,2,3]

In [5]:
import numpy as np

In [7]:
arr = np.array(my_list)

In [8]:
arr

array([1, 2, 3])

In [10]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [11]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [17]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones(4)

array([1., 1., 1., 1.])

In [19]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.random.rand(5)

array([0.69492619, 0.75491946, 0.51761558, 0.04894162, 0.84826798])

In [23]:
np.random.rand(5,5)

array([[0.74718901, 0.12116932, 0.11429085, 0.07071673, 0.54773871],
       [0.14244997, 0.13676517, 0.86716588, 0.31521881, 0.40133603],
       [0.38980303, 0.87223995, 0.32922018, 0.90722231, 0.67850279],
       [0.12777406, 0.71762284, 0.18194234, 0.65841411, 0.52327495],
       [0.37276376, 0.01207816, 0.25993192, 0.27827345, 0.06563447]])

In [24]:
np.random.randn(2)

array([ 0.88534855, -1.47863571])

In [25]:
np.random.randn(4,4)

array([[-0.42675854,  0.87567564,  0.91014533,  1.43624548],
       [-0.53513299,  1.28044313, -1.44488855, -1.07871892],
       [ 1.69526977, -1.7971595 ,  0.38472112,  0.80750253],
       [-0.63241984, -0.66163142, -1.78254498,  0.22158867]])

In [26]:
np.random.randint(1,100)

34

In [27]:
np.random.randint(1,100,10)

array([72, 85, 13, 79, 61, 71, 95, 75,  2, 10])

In [28]:
arr = np.arange(25)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
ranarr = np.random.randint(0,50,10)

In [31]:
ranarr

array([43, 39, 26, 13, 11, 48, 26, 45, 32,  7])

In [32]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
ranarr

array([43, 39, 26, 13, 11, 48, 26, 45, 32,  7])

In [35]:
ranarr.max()

48

In [36]:
ranarr.min()

7

In [37]:
ranarr

array([43, 39, 26, 13, 11, 48, 26, 45, 32,  7])

In [38]:
ranarr.argmax()

5

In [40]:
ranarr.argmin()

9

In [43]:
arr.shape

(25,)

In [46]:
arr = arr.reshape(5,5)

In [48]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
arr.shape

(5, 5)

In [50]:
arr.dtype

dtype('int64')

In [51]:
from numpy.random import randint

In [52]:
randint(2,10)

2